name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@9122525162705ed0676ed066e788f2e531a25bea # v1.0.0
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@9122525162705ed0676ed066e788f2e531a25bea # v1.0.0
    with:
      working-directory: "."
